### PR TITLE
Add triage command

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This command is intended for the addition of priority tags
(high/medium/low) while removing some set of tags, usually a nomination.

See [wiki page](https://github.com/rust-lang/triagebot/wiki/Triage) for usage.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@nikomatsakis I'd appreciate a review of the [wiki page](https://github.com/rust-lang/triagebot/wiki/Triage) to let me know if this looks like the right fit for this feature.

**Comment by spastorino** [comment]
Ohh just found this which we could reuse for the @rust-lang/wg-prioritization but changing `I-nominated` with `I-prioritize`.

**Comment by Dylan-DPC** [comment]
Also need to add P-critical to this

**Comment by nikomatsakis** [comment]
wiki page looks right, fwiw, I missed that ping earlier :)

**Comment by kellda** [comment]
Rebased on master at https://github.com/kellda/triagebot/tree/triage-command

**Pull request closed without merging**
