### PR TITLE
Fix MCP concern syntax hint

### PR DESCRIPTION
**Pull request by apiraino**
Fixing a typo when suggesting the syntax to raise concerns on compiler MCPs (template was implemented in #1747)

### CODE REVIEW

**Comment by ehuss** [comment]
Does rfcbot just ignore these commands because it is not enabled on the repo?

What happens if you do `@rustbot concern` on it?

**Comment by ehuss** [comment]
I'm confused. The link to that comment uses `@rustbot`. Nothing in that PR seems to mention rfcbot.
Does rfcbot also ignore it?
Do you want to change this just to be more consistent with the use of rfcbot in other repositories?

**Comment by apiraino** [comment]
@rfcbot concern this-is-a-test

**Comment by apiraino** [comment]
Ok, no user-visible effects. But the logic in the triagebot to gather concerns needs the `@rfcbot` invocation,  just as [I had implemented](https://github.com/rust-lang/triagebot/blob/4b28086e6b7e7566534a8e936ad9b9acf6105a6c/src/github.rs#L2117) it since the beginning

**Review by ehuss — APPROVED** [review]
Ok, I see, thanks!

**Pull request merged**
