### PR TITLE
Fix (intentional) typos on the triage dashboard

### PR DESCRIPTION
**Pull request by JohnTitor**
Found on https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Triage.20PR.20dashboard/near/230171965.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Hm, I'm feeling like we should probably just use Triage here - it doesn't seem like the typo/intentional misspelling is worth it to me, or at least, I'm not sure what purpose it serves.

**Comment by JohnTitor** [comment]
I think the `<title>` should be the same as this line:
https://github.com/rust-lang/triagebot/blob/34c01cb520c0867232e5eb5da2af927ebabbe8a7/templates/triage/pulls.html#L44

So picking up _toriage_ but if you prefer just _triage_, I think that should be also changed. Probably `Triage dashboard` is the best naming here?

**Comment by Mark-Simulacrum** [comment]
triage dashboard seems reasonable to me

**Comment by JohnTitor** [comment]
Alright, done.

**Pull request merged**
